name: Lint

on:
  workflow_dispatch:

jobs:
  find:
    name: Find add-ons
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Find add-ons
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

  lint:
    name: Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-latest
    needs: find
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Run add-on linter
        uses: home-assistant/actions/helpers/linter@master
        with:
          path: "./${{ matrix.path }}"