name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.1)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Set version
        id: version
        run: |
          VERSION="${{ inputs.version }}"
          # Remove 'v' prefix if present
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT


      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## LibreSpeed Home Assistant Add-on v${{ steps.version.outputs.version }}
            
            ### Installation
            Add this repository to your Home Assistant:
            ```
            https://github.com/${{ github.repository }}
            ```
            
            Then install LibreSpeed from the Add-on Store.
            
            ### What's Changed
            - See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for details
          draft: false
          prerelease: false

  build:
    needs: create-release
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./librespeed"

      - name: Check if add-on should be built
        id: check
        run: |
          if [[ "["aarch64","amd64"]" =~ ${{ matrix.arch }} ]]; then
             echo "build_arch=true" >> $GITHUB_OUTPUT
             echo "image=$(echo "ghcr.io/gtxaspec/{arch}-addon-librespeed" | cut -d'/' -f3)" >> $GITHUB_OUTPUT
          else
             echo "${{ matrix.arch }} is not a valid arch, skipping build"
             echo "build_arch=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        if: steps.check.outputs.build_arch == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/librespeed \
            --image "${{ steps.check.outputs.image }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon